services:
  mysql:
    image: mysql:8.0
    container_name: advanced-sql-practice-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice_sql
    ports:
      - "3307:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
